services:
  event-paiger-app:
    container_name: entertainment-agency-app
    image: entertainment-agency-app-image
    ports:
      - "40482:8082"
    networks:
      - agency-network
    volumes:
      - /data/staticfiles:/data/staticfiles

networks:
  agency-network:
    external: true
